# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Nexu1000!@#$$"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  noteapi:
    image: noteapi
    build: .
    environment:
      DBServer: "sql1"
     #context: .
     #dockerfile: ./Dockerfile
    ports:
      - 8080:80
    #depends_on:
    #  - "sql1"
